name = "vidion"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Configure build output directory for Pages
pages_build_output_dir = ".vercel/output/static"

# Configure routes
[routes]
include = ["/*"]
exclude = []

[build]
command = "npm run build" 